CREATE TABLE IF NOT EXISTS users (
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME    VARCHAR(255) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    PASSWORD    VARCHAR(255) NOT NULL,
    TOKEN       VARCHAR(2048) NOT NULL,
    CREATED_AT  DATETIME NOT NULL DEFAULT NOW()
);